spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/logistics?serverTimezone=Asia/Taipei&useSSL=false&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
app.osrm.base-url=http://localhost:5001